
server:
  port: 8801

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual #开启ack,消费者接受到消息手动确认
        retry:
          max-attempts: 3